[tool.black]
line-length = 99
target-version = ['py310']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-r a --cache-clear"
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::ImportWarning"
]

[tool.mypy]
exclude = "betonyou,tests"
follow_imports = "silent"
ignore_missing_imports = "true"

[isort]
profile = "black"