from setuptools import find_packages, setup

setup(
    name="betonyou",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        "asyncstdlib~=3.9",
        "apscheduler~=3.8",
        "bcrypt==3.2.*",
        "dependency_injector~=4.32",
        "email-validator==1.1.*",
        "fastapi==0.65.*",
        "gspread==3.6.*",
        "pandas~=1.3",
        "phonenumbers~=8.12",
        "pyOpenSSL==20.0.*",
        "requests==2.24.*",
        "shortuuid==1.0.*",
        "sqlalchemy_utils~=0.37",
        "sqlalchemy~=1.4",
        "uvicorn[standard]~=0.11",
        "psycopg2-binary",
    ],
    extras_require={
        "ci": [
            "apiritif",
            "bandit",
            "coverage",
            "elmock",
            "faker",
            "flake8",
            "freezegun",
            "mypy",  # linting on types
            "pytest",
            "yoyo-migrations",
        ],
        "dev": [
            "apiritif",
            "bandit",
            "black",
            "coverage",
            "elmock",
            "faker",
            "flake8",
            "freezegun",
            "isort",
            "mypy",  # linting on types
            "pytest",
            "requests-mock",
            "requests-toolbelt",
            "yoyo-migrations",
            "dramatiq[watch]",
            "debugpy",
        ],
    },
)
